name: barcode-java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '13', '15' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
        check-latest: true
    - name: Build with Gradle
      run: ./gradlew build -x signArchives
      env:
        mavenCentralUsername: ${{ secrets.mavenCentralUsername }}
        mavenCentralPassword: ${{ secrets.mavenCentralPassword }}
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: build/libs

  sign:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
          check-latest: true
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Build with Gradle
        run: ./gradlew build
        env:
          mavenCentralUsername: ${{ secrets.mavenCentralUsername }}
          mavenCentralPassword: ${{ secrets.mavenCentralPassword }}
          ORG_GRADLE_PROJECT_signing.keyId: ${{ secrets.GPG_SIGNING_KEY_ID }}
          ORG_GRADLE_PROJECT_signing.password: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_signing.gnupg.executable: gpg
          ORG_GRADLE_PROJECT_signing.gnupg.keyName: ${{ secrets.GPG_SIGNING_KEY_ID }}