name: barcode-java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '13', '15' ]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: ${{ matrix.java }}
        check-latest: true
    - name: Build with Gradle
      run: ./gradlew build -x signArchives
    - uses: actions/upload-artifact@v2
      with:
        name: Package
        path: build/libs
      env:
        mavenCentralUsername: ${{ secrets.SONATYPE_USER }}
        mavenCentralPassword: ${{ secrets.SONATYPE_PASS }}
